# Blueprint for deploying the BiteSpeed Chatbot Builder on Render

services:
  # Web service - your main application
  - type: web
    name: bitespeed-chatbot-builder
    env: node
    buildCommand: npm install && cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: /api
      - key: PORT
        value: 5000
      - key: MONGODB_URL
        sync: false # This means you'll set it manually on the Render dashboard
