# Blueprint for deploying the BiteSpeed Chatbot Builder on Render

services:
  # Web service - your main application
  - type: web
    name: bitespeed-chatbot-builder
    env: node
    buildCommand: npm run install-all && npm run heroku-postbuild
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URL
        sync: false # This means you'll set it manually on the Render dashboard
